#!/bin/bash

# Descargar e instalar Quarto
curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.deb
sudo dpkg -i quarto-1.4.550-linux-amd64.deb
rm quarto-1.4.550-linux-amd64.
# clonar mi conf de RStudio
cp rstudio-prefs.json ~/.config/rstudio/rstudio-prefs.json
